
- import_tasks: i3.yml
- import_tasks: fonts.yml
- import_tasks: music.yml
- import_tasks: doctools.yml

- name: Install vim and emacs
  kewlfft.aur.aur:
    name:
      - neovim
      - emacs
    state: present
