
- name: Prefer stellarium-bin to stellarium that needs to be compiled
  community.general.pacman:
    name: stellarium
    state: absent
    extra_args: --recursive

# the key needs to be installed by the same user that does the install
- name: Install gpg key
  ansible.builtin.command: gpg --recv-keys BF38D4D02A328DFF
  become: true
  become_user: aur_builder

- name: Install Stellarium-bin
  kewlfft.aur.aur:
    name: stellarium-bin
    state: present
  become: true
  become_user: aur_builder
