

# ubxtool -P 18.00
# ubxtool -p SAVE
# ubxtool -p COLDBOOT

- name: Install gpsd
  kewlfft.aur.aur:
    use: yay
    name:
      - gpsd
    state: present

- name: Enable gpsd service
  systemd:
    enabled: yes
    state: started
    name: gpsd
