- name: Install reflector to manage mirrorlist
  pacman:
    name:
      - reflector

- name: make sure /etc/pacman.d/hooks/ exist
  file:
    path: /etc/pacman.d/hooks/
    state: directory
    mode: '0755'

- name: pacman hook that will run reflector and remove the .pacnew file created every time pacman-mirrorlist gets an upgrade
  copy:
    dest: /etc/pacman.d/hooks/mirrorupgrade.hook
    content: |
      [Trigger]
      Operation = Upgrade
      Type = Package
      Target = pacman-mirrorlist

      [Action]
      Description = Updating pacman-mirrorlist with reflector and removing pacnew...
      When = PostTransaction
      Depends = reflector
      Exec = /bin/sh -c "reflector --country 'Australia' --latest 200 --age 24 --sort rate --save /etc/pacman.d/mirrorlist; rm -f /etc/pacman.d/mirrorlist.pacnew"

- name: update the system
  pacman:
    update_cache: yes
    upgrade: yes
