- name: Ensure group "pia" exists
  ansible.builtin.group:
    name: pia

- name: User Pia
  ansible.builtin.user:
    name: pia

- name: Ensure group "bro" exists
  ansible.builtin.group:
    name: bro

- name: Emergency user
  ansible.builtin.user:
    name: bro
    groups: wheel
    append: true
